[build]
  command = "npm install && npm run build" # your build command
  publish = "dist" # where your production ready code lives AFTER your build command has run
  functions = ".netlify/functions/" # where your production ready lambda functions live AFTER your build command has run
