name: Audit live site
on: push

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
    - name: Audit CTBS
      uses: jakejarvis/lighthouse-action@master
      with:
        url: 'https://www.connecticutbasementsystems.com/'
    - name: Audit Q1BS
      uses: jakejarvis/lighthouse-action@master
      with:
        url: 'https://www.quality1stbasementsystems.com/'
    - name: Auto committing minified files
      uses: stefanzweifel/git-auto-commit-action@v3.0.0
      with:
        commit_message: "Github Action: Auto Minified JS and CSS files"
        branch: ${{ github.ref }}
