name: Audit live site
on: push

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
    - name: Audit CTBS
      uses: jakejarvis/lighthouse-action@master
      with:
        url: 'https://www.connecticutbasementsystems.com/'
    - name: Audit Q1BS
      uses: jakejarvis/lighthouse-action@master
      with:
        url: 'https://www.quality1stbasementsystems.com/'
    - name: Upload results as an artifact
      uses: actions/upload-artifact@master
      with:
        name: report
        path: './report'
