name: Node CI
on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        version: 10.x
    - name: npm install, build, and test
      run: 
        npm install;
        gulp
    - name: Auto committing minified files
      uses: stefanzweifel/git-auto-commit-action@v3.0.0
      with:
        commit_message: "Github Action: Auto Minified JS and CSS files"
        branch: ${{ github.ref }}
